### ISSUE TITLE
[14.0] not possible to reconcile with filled in partner bank account

### ISSUE THREAD

**Issue by bosd** [OCA/account-reconcile#378]
**Steps to reproduce:**

Create or import a bank statement.
Create a statement line, fill in a partner and an ```account_number```.
Validate the statement and do an reconcile.
In the reconcile widget perform an reconcile and  press the validate button.

Following error is shown.
<details>

```

Fout:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/auto/addons/web/controllers/main.py", line 1389, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/auto/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 392, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 365, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/auto/addons/account_reconciliation_widget/models/reconciliation_widget.py", line 49, in process_bank_statement_line
    moves = st_line.with_context(ctx).process_reconciliation(
  File "/opt/odoo/auto/addons/account_reconciliation_widget/models/account_bank_statement.py", line 203, in process_reconciliation
    if self.account_number and self.partner_id and not self.bank_account_id:
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: 'account.bank.statement.line' object has no attribute 'bank_account_id'

```

</details>

Step to double check if it is coming from bank account number:
Go back to the statement. Set to draft. Edit the statement to delete the account number.
Validate the statement again. Do a reconciliation. Press the validate button.
No there is no error. 

p.s. when a fix is made on this module. please see. https://github.com/OCA/account-reconcile/issues/376

**Comment by ozono** [comment]
Fixed on #380
