### ISSUE TITLE
[14.0] Account_reconcile_widget - Regex - odoo server error

### ISSUE THREAD

**Issue by bosd** [OCA/account-reconcile#386]
Create a reconcile model
Set an partner to reconcile to

Input a regular expression:
K36.\(d{2}.\d{2}.\d{3})

Go to your bank account, click the reconcile button.
See the odoo server error.

<detail>

```



Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/auto/addons/web/controllers/main.py", line 1389, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/auto/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 392, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/opt/odoo/custom/src/odoo/odoo/api.py", line 365, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/auto/addons/account_reconciliation_widget/models/reconciliation_widget.py", line 320, in get_bank_statement_data
    results = self.get_bank_statement_line_data(bank_statement_lines.ids)
  File "/opt/odoo/auto/addons/account_reconciliation_widget/models/reconciliation_widget.py", line 238, in get_bank_statement_line_data
    matching_amls = reconcile_model._apply_rules(
  File "/opt/odoo/auto/addons/account/models/account_reconcile_model.py", line 488, in _apply_rules
    if rec_model._is_applicable_for(st_line, partner):
  File "/opt/odoo/auto/addons/account/models/account_reconcile_model.py", line 548, in _is_applicable_for
    or (self['match_' + rule_field] == 'match_regex' and not re.match(rule_term, record_term))
  File "/usr/local/lib/python3.8/re.py", line 191, in match
    return _compile(pattern, flags).match(string)
  File "/usr/local/lib/python3.8/re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/local/lib/python3.8/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/local/lib/python3.8/sre_parse.py", line 962, in parse
    raise source.error("unbalanced parenthesis")
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
re.error: unbalanced parenthesis at position 22



```

<details>

**Comment by pedrobaeza** [comment]
Your regular expression is incorrect.
