### ISSUE TITLE
[14.0] Widget doesn't load

### ISSUE THREAD

**Issue by Joepriesto** [OCA/account-reconcile#388]
Steps to reproduce:

1. Installed by git clone then cp -R into /lib/python3/dist-packages/odoo/addons/
2. Modules menu refreshed installed module
3. Invoicing -> Dashboard -> Click "Reconcile n items"
4. Error below

Same result via other menus.

Error:

Traceback:
Error: QWeb2: Template 'reconciliation' not found
    at Object.exception (https://odoo.hostedbyjoe.com/web/content/205-1da9141/web.assets_common.js:4373:7)
    at Engine._render (https://odoo.hostedbyjoe.com/web/content/205-1da9141/web.assets_common.js:4418:103)
    at Engine.render (https://odoo.hostedbyjoe.com/web/content/205-1da9141/web.assets_common.js:4414:151)
    at Class.renderElement (https://odoo.hostedbyjoe.com/web/content/585-09f43c5/web.assets_backend.js:480:452)
    at Class.prototype.<computed> [as renderElement] (https://odoo.hostedbyjoe.com/web/content/205-1da9141/web.assets_common.js:4607:488)
    at https://odoo.hostedbyjoe.com/web/content/205-1da9141/web.assets_common.js:4935:6

**Comment by pedrobaeza** [comment]
You haven't installed it correctly or your deployment is not correct (maybe because you haven't restarted your service or you try to install it through the "Install addon" option, which is not valid). Anyways, closing, as it's not a problem of the module.
