### ISSUE TITLE
Cron for easy reconcile fails when a reconcile profile never ran

### ISSUE THREAD

**Issue by guewen** [OCA/account-reconcile#39]
`account_easy_reconcile.run_scheduler()` fails when a reconcile profile has no history, because it tries to convert a None value to a date.

```
2014-08-24 19:01:23,878 23112 ERROR openerp openerp.addons.base.ir.ir_cron: Call of self.pool.get('account.easy.reconcile').run_scheduler(cr, uid, *()) failed in Job 52
Traceback (most recent call last):
  File "/srv/openerp/instances/openerp/parts/server/openerp/addons/base/ir/ir_cron.py", line 136, in _callback
    method(cr, uid, *args)
  File "/srv/openerp/instances/openerp/parts/bank-statement-reconcile/account_easy_reconcile/easy_reconcile.py", line 384, in run_scheduler
    reconciles.sort(key=_get_date)
  File "/srv/openerp/instances/openerp/parts/bank-statement-reconcile/account_easy_reconcile/easy_reconcile.py", line 376, in _get_date
    DEFAULT_SERVER_DATETIME_FORMAT)
TypeError: must be string, not None

```

**Comment by guewen** [comment]
Only in https://github.com/OCA/bank-statement-reconcile/pull/16 so I close this issue and fix directly in the PR.
