### ISSUE TITLE
Bank/Cash reconciliation error

### ISSUE THREAD

**Issue by Desmor01** [OCA/account-reconcile#423]
1. When clicking on the pending reconciliation items next error message is displayed:

Error:

Traceback:
Error: QWeb2: Template 'reconciliation' not found
    at Object.exception (http://localhost:8069/web/content/114-fa45a37/web.assets_common.js:4406:7)
    at Engine._render (http://localhost:8069/web/content/114-fa45a37/web.assets_common.js:4451:103)
    at Engine.render (http://localhost:8069/web/content/114-fa45a37/web.assets_common.js:4447:151)
    at Class.renderElement (http://localhost:8069/web/content/157-94d4995/web.assets_backend.js:485:452)
    at Class.prototype.<computed> [as renderElement] (http://localhost:8069/web/content/114-fa45a37/web.assets_common.js:4644:488)
    at http://localhost:8069/web/content/114-fa45a37/web.assets_common.js:4986:6
.

**Expected behavior**
I expect that the reconciliation screen to be displayed in order to reconcile the open items

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)
Odoo community V14.0

**Comment by echarp** [comment]
I suppose this is a setup bug, or else nobody would be able to use it, no?

Found it following: https://www.mallory-marcot.com/blog/devblog-1/post/le-lettrage-des-ecritures-comptables-avec-odoo-14-community-edition-16

Which includes some steps to install it. Seems to work well, I do have the proper reconciliation button!

**Comment by echarp** [comment]
After some tweaking and restart, it seems to work as expected.

Probably some setup/installation issue.
