### ISSUE TITLE
[14.0][Bug] account_reconcile_widget: The application does not work in a group with inheritance

### ISSUE THREAD

**Issue by alodoanhnhan** [OCA/account-reconcile#441]
When I decentralize personnel in the form of groups (group of accountants, group of chief accountants, group of directors,...), these groups are inherited (for example, the group of chief accountants inherits the group of accountants. )
At this time, the application only works well for the accounting group, but not for the chief accountant group and higher groups (directors, administration groups).
When using the group of chief accountants to reconcile in the bank statement, it reported the following error:
```

Odoo Server Error
Traceback (most recent call last):
  File "E:\Program Files\Odoo\server\odoo\addons\base\models\ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "E:\Program Files\Odoo\server\odoo\http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "E:\Program Files\Odoo\server\odoo\http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "E:\Program Files\Odoo\server\odoo\service\model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "E:\Program Files\Odoo\server\odoo\http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "E:\Program Files\Odoo\server\odoo\http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "E:\Program Files\Odoo\server\odoo\http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "E:\Program Files\Odoo\server\odoo\addons\web\controllers\main.py", line 1392, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "E:\Program Files\Odoo\server\odoo\addons\web\controllers\main.py", line 1384, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "E:\Program Files\Odoo\server\odoo\api.py", line 395, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "E:\Program Files\Odoo\server\odoo\api.py", line 368, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "e:\program files\odoo\server\addons_1\account_reconciliation_widget\models\reconciliation_widget.py", line 330, in get_bank_statement_data
    results = self.get_bank_statement_line_data(bank_statement_lines.ids)
  File "e:\program files\odoo\server\addons_1\account_reconciliation_widget\models\reconciliation_widget.py", line 242, in get_bank_statement_line_data
    partner_map = self._get_bank_statement_line_partners(bank_statement_lines)
  File "e:\program files\odoo\server\addons_1\account_reconciliation_widget\models\reconciliation_widget.py", line 203, in _get_bank_statement_line_partners
    self._cr.execute(query, params)
  File "<decorator-gen-3>", line 2, in execute
  File "E:\Program Files\Odoo\server\odoo\sql_db.py", line 101, in check
    return f(self, *args, **kwargs)
  File "E:\Program Files\Odoo\server\odoo\sql_db.py", line 298, in execute
    res = self._obj.execute(query, params)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Program Files\Odoo\server\odoo\http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "E:\Program Files\Odoo\server\odoo\http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
psycopg2.errors.UndefinedTable: relation "p3" does not exist
LINE 10: ...(SELECT "res_users".id FROM "res_users" LEFT JOIN "p3" AS "r...

```
**Note: I also used the base_user_role app but it keeps giving me the error. If I don't create inheritance group then the app works fine. I don't know if anyone has made this mistake like me?**

**Comment by pedrobaeza** [comment]
This should be fixed after #427
