### ISSUE TITLE
[15] account_reconciliation_widget assets error

### ISSUE THREAD

**Issue by klando** [OCA/account-reconcile#469]
## Module

**account_reconciliation_widget**

## Describe the bug

```
UncaughtPromiseError > KeyNotFoundError
Uncaught Promise > Cannot find manual_reconciliation_view in this registry!

KeyNotFoundError: Cannot find manual_reconciliation_view in this registry!
    at Registry.get (https://DOMAIN/web/assets/568-7ce748b/web.assets_backend.min.js:929:76)
    at _executeClientAction (https://DOMAIN/web/assets/568-7ce748b/web.assets_backend.min.js:2279:87)
    at Object.doAction (https://DOMAIN/web/assets/568-7ce748b/web.assets_backend.min.js:2296:192)
    at async Object.selectMenu (https://DOMAIN/web/assets/568-7ce748b/web.assets_backend.min.js:2398:1)
```

## To Reproduce
**Affected versions**: 15

1. Install the addon
2. (regenerate assets)
3. (full refresh of page)
4. click on the "reconcile" menu

**Expected behavior**

Something without error

**Comment by pedrobaeza** [comment]
Is this reproducible in runboat?

**Comment by klando** [comment]
> Is this reproducible in runboat?

I don't find the reconcile menu in the runbot...ok, updated ACL for that.

No errors there...

**Comment by klando** [comment]
so, as it is working in runbot I suppose the problem is on my side only (maybe due to another addon ?)
Any pointer/assistance to debug will be greatly appreciated..

**Comment by pedrobaeza** [comment]
I would start installing the module in a fresh database:

- If not working, it's your installation/deployment method.
- If working, it's an extra module that cause the problem.

**Comment by klando** [comment]
tks @pedrobaeza, I'll try. 
I close this issue.

**Comment by klando** [comment]
solution here to the problem: just upgrade the addon (from web UI), fixes the situation.

**Comment by bjustizglez** [comment]
Tengo la misma situación y no se resolvió actualizando

**Comment by DAVIDRD91** [comment]
I have the same situation.

how to update add-on (from web UI)

**Comment by pleirb** [comment]
The same thing happens to me, I am testing from an odoo that already has data and with other plugins installed (mostly OCA)
Module: **account_partner_reconcile**
![image](https://github.com/OCA/account-reconcile/assets/2092475/1d8e7b2b-d2d0-42a0-a753-4e3081438754)

```
KeyNotFoundError: Cannot find manual_reconciliation_view in this registry!
    at Registry.get (https://demo.hfnet.uy/web/assets/39996-401c62d/web.assets_backend.min.js:945:76)
    at _executeClientAction (https://demo.hfnet.uy/web/assets/39996-401c62d/web.assets_backend.min.js:2309:87)
    at doAction (https://demo.hfnet.uy/web/assets/39996-401c62d/web.assets_backend.min.js:2326:192)
    at async Object.doActionButton (https://demo.hfnet.uy/web/assets/39996-401c62d/web.assets_backend.min.js:2333:196)
```

**Comment by pleirb** [comment]
> **account_partner_reconcile**

Curiously installing the module: **account_reconciliation_widget**
Everything works, so perhaps what is missing is that the module: **account_partner_reconcile** has a dependency on: **account_reconciliation_widget**
