### ISSUE TITLE
Uncaught Promise > Cannot find bank_statement_reconciliation_view in this registry!

### ISSUE THREAD

**Issue by mdfaisalpapa** [OCA/account-reconcile#488]
## Module
account_reconciliation_widget

## Describe the bug
Installed the account_reconciliation_widget available at https://odoo-community.org/shop/account-reconciliation-widget-8893?search=reconciliation_widget#attr=19070

When I click on the reconcile button i get the following error

KeyNotFoundError: Cannot find bank_statement_reconciliation_view in this registry!
    at Registry.get (http://localhost:8069/web/assets/647-5be843b/web.assets_backend.min.js:936:76)
    at _executeClientAction (http://localhost:8069/web/assets/647-5be843b/web.assets_backend.min.js:2284:87)
    at doAction (http://localhost:8069/web/assets/647-5be843b/web.assets_backend.min.js:2301:192)
    at async Object.doActionButton (http://localhost:8069/web/assets/647-5be843b/web.assets_backend.min.js:2308:196)

## To Reproduce
**Affected versions**: 15

1. Install the module on odoo 15
2. accounting dash board
3. click on reconcile

**Comment by pedrobaeza** [comment]
Are you able to reproduce it using the runboat link in the README?

**Comment by mdfaisalpapa** [comment]
The issue got resolved on rebooting the server.
