### ISSUE TITLE
[15.0][account_reconciliation_widget] UndefinedTable: relation "res_company_p3_rel" does not exist 

### ISSUE THREAD

**Issue by aferreroc** [OCA/account-reconcile#520]
## Module
account_reconciliation_widget

## Describe the bug
...
  File "/opt/odoo/v15/account-reconcile/account_reconciliation_widget/models/reconciliation_widget.py", line 331, in get_bank_statement_data
    results = self.get_bank_statement_line_data(bank_statement_lines.ids)
  File "/opt/odoo/v15/account-reconcile/account_reconciliation_widget/models/reconciliation_widget.py", line 243, in get_bank_statement_line_data
    partner_map = self._get_bank_statement_line_partners(bank_statement_lines)
  File "/opt/odoo/v15/account-reconcile/account_reconciliation_widget/models/reconciliation_widget.py", line 204, in _get_bank_statement_line_partners
    self._cr.execute(query, params)
  File "<decorator-gen-3>", line 2, in execute
  File "/opt/odoo/v15/OCB/odoo/sql_db.py", line 90, in check
    return f(self, *args, **kwargs)
  File "/opt/odoo/v15/OCB/odoo/sql_db.py", line 313, in execute
    res = self._obj.execute(query, params)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/v15/OCB/odoo/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/v15/OCB/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
psycopg2.errors.
LINE 12:                             SELECT 1 FROM "res_company_p3_re...

## To Reproduce
**Affected versions**: 15.0.1.2.2

1.Import the n43, Public it
2. Click the wizard to reconcilie, then the error occurs 

**Expected behavior**
No error expected, reconciliation done

**Additional context**
Ubuntu 20.04.5 LTS
Python 3.8 vitualenv
Postgresql 12

**Comment by initiumsys** [comment]
I think is similar to #427

**Comment by pedrobaeza** [comment]
Yes, already fixed. Update your code.
