### ISSUE TITLE
[15.0] account_reconciliation_widget - Error Uncaught Promise > '2&#x27;553.12' is no valid float

### ISSUE THREAD

**Issue by clxadmin** [OCA/account-reconcile#567]
Module
[15.0] account_reconciliation_widget 15.0.1.2.9

Desciption
camt.53 file is imported and I start reconcilation this error happens only to some specific lines.

Error:
UncaughtPromiseError
Uncaught Promise > '2&#x27;553.12' is no valid float

Error: '2&#x27;553.12' ist kein gülter float
    at parseFloat (https://company.ch/web/assets/4178-6dbbf69/web.assets_backend.min.js:4228:82)
    at Object.parseMonetary [as monetary] (https://company.ch/web/assets/4178-6dbbf69/web.assets_backend.min.js:4235:156)
    at Class._formatQuickCreate (https://company.ch/web/assets/4178-6dbbf69/web.assets_backend.min.js:10928:1072)
    at Class.createProposition (https://company.ch/web/assets/4178-6dbbf69/web.assets_backend.min.js:10880:469)
    at Class.changeMode (https://company.ch/web/assets/4178-6dbbf69/web.assets_backend.min.js:10878:38)
    at https://company.ch/web/assets/4178-6dbbf69/web.assets_backend.min.js:10874:640

Note: I was facing some information like '#' used in one transaction line in the bank statement camt.53 file .. since then I have this issue

**Comment by pedrobaeza** [comment]
You should try to reproduce the problem in runboat.

**Comment by clxadmin** [comment]
I was aible to reproduce it local on a fresh odoo database - if I import multiple camt.53 files, containing payment lines with information like #Number of Invoice, - this '#' seems to be a problem with reconcile for follow up camt.53 imports.

It is more the question what does the error: Error Uncaught Promise > '2&#x27;553.12' is no valid float  -- pointing out?

**Comment by pedrobaeza** [comment]
Let's see if someone notices anything about that.
