### ISSUE TITLE
[16.0] account_reconcile_oca reset (unreconcile fails)

### ISSUE THREAD

**Issue by nagybal** [OCA/account-reconcile#579]
## Module
account_reconcile_oca

## Describe the bug
If I hit reset on certain matches to be uncreconciled, the below Odoo Server Error appears:

```
RPC_ERROR
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1584, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1611, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1815, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/account_reconcile_oca/models/account_bank_statement_line.py", line 564, in unreconcile_bank_line
    return getattr(self, "_unreconcile_bank_line_%s" % self.reconcile_mode)(
AttributeError: 'account.bank.statement.line' object has no attribute '_unreconcile_bank_line_False'

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    at makeErrorFromResponse (http://IPaddress:8069/web/assets/409-c66cc84/web.assets_backend.min.js:985:163)
    at XMLHttpRequest.<anonymous> (http://IPaddress:8069/web/assets/409-c66cc84/web.assets_backend.min.js:993:13)
```

## To Reproduce

**Additional context**
1. The strange thing is that not all of the entries are producing this error.
2. If I click the "View Move" button, I can unreconciled the move, but still the widget considers it as a reconciled entry

![Screen Shot 2023-08-23 at 16 10 02](https://github.com/OCA/account-reconcile/assets/27618042/16d582ba-1e6f-413e-a81c-e5d502000d86)

![Screen Shot 2023-08-23 at 16 06 12](https://github.com/OCA/account-reconcile/assets/27618042/46b25347-f5f8-4266-be4f-a1beabb277b3)

**Comment by nagybal** [comment]
I have noticed, that this issue occurs when the reconciliation was unbalanced.
1. I do not understand how it is possible that **account_reconcile_oca** allows unbalanced entries to be reconciled.
2. If we do not want to fix the below, as it is considered a feature, we need a fix for the reset!
![Screen Shot 2023-08-25 at 14 43 35](https://github.com/OCA/account-reconcile/assets/27618042/67b11c33-ffd9-4559-94b7-81cb872efccb)

**Comment by nagybal** [comment]
@etobella I found an other one. Could You please take a look?

**Comment by etobella** [comment]
Sure! Did you test the last option I sent? Did it work to you?

**Comment by etobella** [comment]
How did you manage to reconcile that move? I mean, I cannot do that (and shouldn't be able to...)

**Comment by nagybal** [comment]
> How did you manage to reconcile that move? I mean, I cannot do that (and shouldn't be able to...)

Like this. I have just created a transaction on the last database (for the commit 994ff0a16c3a)
![Screen Shot 2023-08-26 at 9 00 59](https://github.com/OCA/account-reconcile/assets/27618042/fc13894a-3c7a-4421-80b5-1673e7c0ad23)

It is like some kind of part payment.

**Comment by etobella** [comment]
But the result had a suspense account, and that should be impossible, It might happen when resting a move conciled from another way, but not what you said :thinking:

**Comment by nagybal** [comment]
I am not sure what the intention of this feature was. Let us leave it like this then. 

The bug, I am reporting here is that reconciliation is impossible to reset. Do You know why is that?

**Comment by etobella** [comment]
Well, it seems that it was reconciled using another method :thinking: 

I will fix it using the standard usage in case we didn't have the information there :disappointed:

**Comment by nagybal** [comment]
I have started to work my statements using 91e974803f95ea03e52239dc7245cb5cacb8c88d

I can reset (unreconcile) these problematic transactions. But if I try to reconcile them with the right invoice, I get the below server error:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1584, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1611, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1815, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/dataset.py", line 42, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 6510, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 6221, in _onchange_eval
    method_res = method(self)
  File "/usr/lib/python3/dist-packages/odoo/addons/account_reconcile_oca/models/account_bank_statement_line.py", line 138, in _onchange_add_account_move_line_id
    self.reconcile_data_info = self._recompute_suspense_line(
  File "/usr/lib/python3/dist-packages/odoo/addons/account_reconcile_oca/models/account_bank_statement_line.py", line 147, in _recompute_suspense_line
    reconcile_auxiliary_id = self._compute_exchange_rate(
  File "/usr/lib/python3/dist-packages/odoo/addons/account_reconcile_oca/models/account_bank_statement_line.py", line 391, in _compute_exchange_rate
    or any(line["currency_id"] != line["line_currency_id"] for line in data)
  File "/usr/lib/python3/dist-packages/odoo/addons/account_reconcile_oca/models/account_bank_statement_line.py", line 391, in <genexpr>
    or any(line["currency_id"] != line["line_currency_id"] for line in data)
KeyError: 'line_currency_id'

The above server error caused the following client error:
null
```

**Comment by etobella** [comment]
You should clean the conciliation and then it should work, however, this shows an error, so I will try to fix it :wink:

**Comment by nagybal** [comment]
> You should clean
Thank You! You are the best!

I was always wondering what this button does. What is the difference between "reset" and "cleaning"? 
Why not to automate this cleaning?
![Screenshot 2023-09-06 at 9 56 10](https://github.com/OCA/account-reconcile/assets/27618042/25f96541-5e9c-4d26-95fa-65a5c192bf81)

**Comment by etobella** [comment]
Reset is for unreconciling a reconciled line.

Clean is for removing all your work and reexecuting accounting models (if existent)

**Comment by pedrobaeza** [comment]
Does "Undo reconciliation" fit (by length) to be more specific?

**Comment by nagybal** [comment]
I believe the "Clean" is short enough. Is is possible to add these mouseover hovering text boxes like those little question marks have?

Like this one?
![Screenshot 2023-09-08 at 15 40 44](https://github.com/OCA/account-reconcile/assets/27618042/ca1f4e6a-bcff-4403-82aa-8a5ba07371c7)

**Comment by etobella** [comment]
We might, not so hard, we should need to add a help description there. However, it fits rightly right now, so I am not sure if we need to do the change
