### ISSUE TITLE
[16.0.1.2.2] account_reconcile_oca upgrade fails

### ISSUE THREAD

**Issue by nagybal** [OCA/account-reconcile#590]
## Module
account_reconcile_oca version: 16.0.1.2.2

## Describe the bug
When I try to upgrade the module on my live server, I get the below error
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1584, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1611, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1815, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-80>", line 2, in button_immediate_upgrade
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 647, in button_immediate_upgrade
    return self._button_immediate_function(type(self).button_upgrade)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 580, in _button_immediate_function
    registry = modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "<decorator-gen-14>", line 2, in new
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 90, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 484, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 372, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 183, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/usr/lib/python3/dist-packages/odoo/modules/migration.py", line 180, in migrate_module
    mod = load_script(pyfile, name)
  File "/usr/lib/python3/dist-packages/odoo/modules/migration.py", line 25, in load_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/odoo/addons/account_reconcile_oca/migrations/16.0.1.2.0/pre-migration.py", line 1, in <module>
    from openupgradelib import openupgrade
ModuleNotFoundError: No module named 'openupgradelib'

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    RPCError@http://34.77.110.20:8069/web/assets/478-8060683/web.assets_backend.min.js:981:274
    makeErrorFromResponse@http://34.77.110.20:8069/web/assets/478-8060683/web.assets_backend.min.js:985:163
    jsonrpc/promise</<@http://34.77.110.20:8069/web/assets/478-8060683/web.assets_backend.min.js:993:34
```

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by nagybal** [comment]
@etobella the addon we have been working on, fails to upgrade. Could You please take a look?

**Comment by etobella** [comment]
The problem is that you did not install openupgradelib on your server. If you install it , it should work properly :wink:

**Comment by nagybal** [comment]
I see. It is rather strange because it is not in the account-reconcile repository and it was not a requirement before. I was trying to figure it by its description. What is does exactly?

**Comment by etobella** [comment]
it is not a requirement, but it is something recomended if you use OCA. This library simplifies the migration scripts. A lot of modules on OCA that needs a migration use this library.  I recomended you to install it :wink:

**Comment by nagybal** [comment]
The [openupgradelib](https://github.com/OCA/openupgradelib) is not an option. It became a requirement of the reconciliation module. I just don't get it, as we are not migrating between major odoo versions.

I have installed openupgradelib using the below command and account_reconcile_oca updates now! Thank You for the help!
`sudo pip3 install --ignore-installed git+https://github.com/OCA/openupgradelib.git@master`

Do You know why it was a requirement for this module upgrade? What is the feature?

**Comment by nagybal** [comment]
one sec :) i forgot to pip as root
