### ISSUE TITLE
Error when running on V.17: TypeError: Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by Ludwig-Graef** [OCA/account-reconcile#625]
Hi everyone,
I know this is a bit early, but I am trying to migrate the tool to odoo version 17. 
I have made some progress on it and would like to share it once/if I manage to finish this. 
<br>
I was wondering if anyone has already tried this so they could share their knowledge with me.
<br>
About my problem:
    1. Install account-reconcile v 16
    2. ... Replace states and attrs ...
    3. Click on Accounting/Accounting/Reconcile
<br>
Error:
OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
    at handleError (web/assets/e4c4115/web.assets_web.min.js:916:101)
    at App.handleError (web/assets/e4c4115/web.assets_web.min.js:1543:29)
    at Fiber._render (web/assets/e4c4115/web.assets_web.min.js:941:19)
    at Fiber.render (web/assets/e4c4115/web.assets_web.min.js:939:6)
    at ComponentNode.initiateRender (web/assets/e4c4115/web.assets_web.min.js:1007:47)

Caused by: TypeError: Cannot read properties of undefined (reading 'name')
    at Field.template (eval at compile (web/assets/e4c4115/web.assets_web.min.js:1501:374), <anonymous>:16:92)
    at Fiber._render (web/assets/e4c4115/web.assets_web.min.js:940:96)
    at Fiber.render (web/assets/e4c4115/web.assets_web.min.js:939:6)
    at ComponentNode.initiateRender (web/assets/e4c4115/web.assets_web.min.js:1007:47)

<br>
<br>
<br>
If anyone already knows how to solve this, I would be very grateful. 
Thanks in advance for the help.

**Comment by enis-flexpos** [comment]
any progress on this, I stumbled on same problem, cannot even open Record Rules view.......

**Comment by Ludwig-Graef** [comment]
Hey, 
I ended up buying this module: https://apps.odoo.com/apps/modules/17.0/oi_bank_reconciliation

Works quite well for my purpose.

**Comment by pedrobaeza** [comment]
Already migrated to 17.
