### ISSUE TITLE
[14.0] Account Reconcile Widget don't works in account dashboard

### ISSUE THREAD

**Issue by hromero99** [OCA/account-reconcile#628]
## Module
account-reconcile-widget

## Describe the bug
After import the bank statement, when click inside the reconcile button inside the account dashboard crash and can't enter inside the reconcile screen 
## To Reproduce
**Affected versions**: 14.0

1. Install account-reconcile-widget
2. Import bank statement
3. Click inside reconcile

**Expected behavior**

**Additional context**
Currently using odoo 14.0. The error is related with the SQL automatic generated.

```
Traceback (most recent call last):
  File "/odoo/odoo/http.py", line 652, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
psycopg2.ProgrammingError: syntax error at or near "aml"
LINE 42: ...d = 20727)) AND aml.date >= '2022-08-02'::dateAND [aml.id](http://aml.id/) NOT...
```

**Comment by hromero99** [comment]
Just in case anyone need to works as a "temporal solution" far away the final solution, can enter inside Odoo/account and make the changes:
![Captura de pantalla 2024-02-02 a las 12 56 16](https://github.com/OCA/account-reconcile/assets/14032260/562dc563-0b2f-4b7f-898d-8b697a80dff5)

`  if self.past_months_limit:
             date_limit = fields.Date.context_today(self) - relativedelta(months=self.past_months_limit)
-            query += "AND aml.date >= %(aml_date_limit)s"
+            query += " AND aml.date >= %(aml_date_limit)s"
             params['aml_date_limit'] = date_limit
 
         # Filter out excluded account.move.line.
         if excluded_ids:
-            query += 'AND aml.id NOT IN %(excluded_aml_ids)s'
+            query += ' AND aml.id NOT IN %(excluded_aml_ids)s'
             params['excluded_aml_ids'] = tuple(excluded_ids)
`
I know isn't the best solution, but works...
