### ISSUE TITLE
[16.0]account_statement_base? : impossible to change start/end balance

### ISSUE THREAD

**Issue by flotho** [OCA/account-reconcile#697]
## Module
Not sure of the module source of the issue from now.

## Describe the bug

while tryi to change the end or initial or end balance of a statement, the following exception is thrown

```
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/home/florent.thomas/DEV/_ProjetsOdoo/MindAndGo16/odoo/odoo/api.py", line 1007, in get
    cache_value = field_cache[record._ids[0]]
                  ~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: <NewId origin=21>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/florent.thomas/DEV/_ProjetsOdoo/MindAndGo16/odoo/odoo/fields.py", line 1161, in __get__
    value = env.cache.get(record, self)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florent.thomas/DEV/_ProjetsOdoo/MindAndGo16/odoo/odoo/api.py", line 1014, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: 'account.bank.statement.line(<NewId origin=21>,).running_balance'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/florent.thomas/DEV/_ProjetsOdoo/MindAndGo16/odoo/odoo/http.py", line 1651, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florent.thomas/DEV/_ProjetsOdoo/MindAndGo16/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
             ^^^^^^
  File "/home/florent.thomas/DEV/_ProjetsOdoo/MindAndGo16/odoo/odoo/http.py", line 1678, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florent.thomas/DEV/_ProjetsOdoo/MindAndGo16/odoo/odoo/http.py", line 1882, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florent.thomas/DEV/_ProjetsOdoo/MindAndGo16/odoo/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florent.thomas/DEV/_ProjetsOdoo/MindAndGo16/odoo/odoo/http.py", line 734, in route_wrapper
    result = endpoint(self, *args, **params_ok)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florent.thomas/DEV/Odoo_Server_And_Libs/Servers_16.0/OCB/addons/web/controllers/dataset.py", line 42, in call_kw
    return self._call_kw(model, method, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florent.thomas/DEV/Odoo_Server_And_Libs/Servers_16.0/OCB/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florent.thomas/DEV/_ProjetsOdoo/MindAndGo16/odoo/odoo/api.py", line 468, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florent.thomas/DEV/_ProjetsOdoo/MindAndGo16/odoo/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florent.thomas/DEV/_ProjetsOdoo/MindAndGo16/odoo/odoo/models.py", line 6575, in onchange
    snapshot0 = Snapshot(record, nametree, fetch=(not first_call))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florent.thomas/DEV/_ProjetsOdoo/MindAndGo16/odoo/odoo/models.py", line 6388, in __init__
    self.fetch(name)
  File "/home/florent.thomas/DEV/_ProjetsOdoo/MindAndGo16/odoo/odoo/models.py", line 6396, in fetch
    self[name] = [Snapshot(line, tree[name]) for line in record[name]]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florent.thomas/DEV/_ProjetsOdoo/MindAndGo16/odoo/odoo/models.py", line 6396, in <listcomp>
    self[name] = [Snapshot(line, tree[name]) for line in record[name]]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florent.thomas/DEV/_ProjetsOdoo/MindAndGo16/odoo/odoo/models.py", line 6388, in __init__
    self.fetch(name)
  File "/home/florent.thomas/DEV/_ProjetsOdoo/MindAndGo16/odoo/odoo/models.py", line 6398, in fetch
    self[name] = record[name]
                 ~~~~~~^^^^^^
  File "/home/florent.thomas/DEV/_ProjetsOdoo/MindAndGo16/odoo/odoo/models.py", line 5956, in __getitem__
    return self._fields[key].__get__(self, self.env.registry[self._name])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florent.thomas/DEV/_ProjetsOdoo/MindAndGo16/odoo/odoo/fields.py", line 1219, in __get__
    raise ValueError(f"Compute method failed to assign {missing_recs}.{self.name}")
ValueError: Compute method failed to assign account.bank.statement.line(<NewId origin=21>,).running_balance

The above server error caused the following client error:
null
```

## To Reproduce
**Affected versions**:
* 16.0

1. Run an OCB installation
2. Try to change the end or initial or end balance of a statement

**Expected behavior**
No error, proper recompute

**Additional context**

Identified a bug here : https://github.com/odoo/odoo/issues/171077 but I didn't succeed in reproducing neither in OE https://68263739-16-0-all.runbot128.odoo.com/web?debug=1#action=573&active_id=8&model=account.bank.statement&view_type=list&cids=1&menu_id=633 nor https://68256574-16-0-all.runbot119.odoo.com/web?debug=1#id=1&cids=1&menu_id=311&action=490&active_id=9&model=account.bank.statement&view_type=form 
On an OCB with runboAt we have the issue : http://oca-account-reconcile-16-0-6adc75071815.runboat.odoo-community.org/web#id=1&cids=1&menu_id=121&action=255&active_id=7&model=account.bank.statement&view_type=form 

I've uninstalled account_statement_base and I succeed to change end/start balance on a simplier view : 
![image](https://github.com/user-attachments/assets/cf2561e0-a117-46d9-b90e-9e33ce8137cf)

**Comment by flotho** [comment]
Hi @alexis-via ,
hope you're doing well.
I'm facing this issue on account_statement_base, did you already faced this ?
Regards

**Comment by pedrobaeza** [comment]
Notified to fail also in 17: #698

**Comment by MatSarr** [comment]
Hi,
same error here.

**Comment by victoralmau** [comment]
https://github.com/odoo/odoo/pull/182497

**Comment by pedrobaeza** [comment]
Can we fix it in this module instead of Odoo base? Not sure they will have the problem in enterprise.
