### ISSUE TITLE
[17.0][account_statement_base] cannot change balance_start in account_bank_statement form view

### ISSUE THREAD

**Issue by cvinh** [OCA/account-reconcile#698]
## Module
account_statement_base

## Steps to reproduce the bug
Go to runboat v17
open the demo bank statement
try to modify balance_start in the form view

**Additional context**
Here is the traceback
Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 1783, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/opt/odoo/odoo/http.py", line 1810, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/opt/odoo/odoo/http.py", line 2014, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/opt/odoo/odoo/addons/base/models/ir_http.py", line 222, in _dispatch
    result = endpoint(**request.params)
  File "/opt/odoo/odoo/http.py", line 759, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo/addons/web/controllers/dataset.py", line 24, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/dataset.py", line 20, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 468, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/addons/web/models/models.py", line 1029, in onchange
    snapshot0 = RecordSnapshot(record, fields_spec, fetch=(not first_call))
  File "/opt/odoo/addons/web/models/models.py", line 1168, in __init__
    self.fetch(name)
  File "/opt/odoo/addons/web/models/models.py", line 1181, in fetch
    self[field_name] = {line.id: RecordSnapshot(line, sub_fields_spec) for line in lines}
  File "/opt/odoo/addons/web/models/models.py", line 1181, in <dictcomp>
    self[field_name] = {line.id: RecordSnapshot(line, sub_fields_spec) for line in lines}
  File "/opt/odoo/addons/web/models/models.py", line 1168, in __init__
    self.fetch(name)
  File "/opt/odoo/addons/web/models/models.py", line 1183, in fetch
    self[field_name] = self.record[field_name]
  File "/opt/odoo/odoo/models.py", line 6649, in __getitem__
    return self._fields[key].__get__(self, self.env.registry[self._name])
  File "/opt/odoo/odoo/fields.py", line 1216, in __get__
    raise ValueError(f"Compute method failed to assign {missing_recs}.{self.name}")
ValueError: Compute method failed to assign account.bank.statement.line(<NewId origin=2>, <NewId origin=1>).running_balance

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    RPC_ERROR
        at makeErrorFromResponse (http://oca-account-reconcile-17-0-ca9918bbe41d.runboat.odoo-community.org/web/assets/7b4b8d8/web.assets_web.min.js:2888:163)
        at XMLHttpRequest.<anonymous> (http://oca-account-reconcile-17-0-ca9918bbe41d.runboat.odoo-community.org/web/assets/7b4b8d8/web.assets_web.min.js:2892:13)

**Comment by pedrobaeza** [comment]
Duplicated of #697
