### ISSUE TITLE
[16] account_reconcile_oca: javascript error when selecting an entry in "bank reconcile"

### ISSUE THREAD

**Issue by beschauer-swp** [OCA/account-reconcile#750]
Given 
- cash journal entries from a closed PoS session. 

When 
- going to "Invoicing / Accounting / Journal Entries"
- opening one of the cash journal entries related to PoS
- go to "Bank reconcile"
- select a "Reconciled" entry on the left.

Then 
- a JavaScript error is thrown. 
      
      TypeError: Cannot read properties of undefined (reading 'model')
          at ReconcileController.selectRecord (http://localhost:8069/web/assets/174-7098bb0/web.assets_backend.min.js:14206:94)
          at ReconcileController.openRecord (http://localhost:8069/web/assets/174-7098bb0/web.assets_backend.min.js:14209:31)
          at ReconcileKanbanRecord.onGlobalClick (http://localhost:8069/web/assets/174-7098bb0/web.assets_backend.min.js:4417:410)
          at Object.mainEventHandler (http://localhost:8069/web/assets/173-8e504a5/web.assets_common.min.js:2002:77)
          at HTMLDivElement.listener (http://localhost:8069/web/assets/173-8e504a5/web.assets_common.min.js:1175:15)
          
 It comes from https://github.com/OCA/account-reconcile/blob/16.0/account_reconcile_oca/static/src/js/reconcile/reconcile_controller.esm.js#L116
 `this.form_controller` is undefined.
 

![Screenshot 2024-11-19 at 09 32 42](https://github.com/user-attachments/assets/f0610fd1-3ee6-4a48-96fc-b9f788af670d)

**Comment by beschauer-swp** [comment]
I can confirm that the linked PR fixes the issue. Thanks a lot!
